# GNU Backgammon Research Environment - Gitpod Configuration

image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more: https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Setup GNU Backgammon Environment
    init: |
      echo "🚀 Setting up GNU Backgammon Research Environment..."
      # Install system dependencies
      sudo apt-get update
      sudo apt-get install -y gnubg python3-dev
      
      # Install Python dependencies
      if [ -f requirements.txt ]; then
        pip3 install --user -r requirements.txt
      fi
      
      # Test installation
      gnubg --version
      
      # Create output directory
      mkdir -p output
      
      echo "✅ Setup complete! 🎉"
      echo ""
      echo "🎮 Try running: python3 main.py --help"
    command: |
      echo "🎲 GNU Backgammon Research Environment is ready!"
      echo ""
      echo "🚀 Quick commands:"
      echo "  python3 main.py                    # Run single game"
      echo "  python3 main.py --n 5              # Run 5 games"
      echo "  python3 main.py --a1 RandomAgent --a2 DebugAgent --n 3"
      echo ""
      echo "📚 Check README.md for full documentation"

# List the ports to expose. Learn more: https://www.gitpod.io/docs/config-ports/
ports: []

# Configure VS Code extensions
vscode:
  extensions:
    - ms-python.python
    - ms-python.pylint
    - ms-python.black-formatter
    - ms-toolsai.jupyter
    - redhat.vscode-yaml
    - ms-vscode.makefile-tools

# Enable workspace sharing
workspaceLocation: "."